### ISSUE TITLE
Moving builds from Travis to Strider

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-control#20]
@smashwilson To leverage the PR builder capability, repositories require Strider builds. Were you planning to create those builds for the DevDoc repositories?

**Comment by smashwilson** [comment]
I'd had some designs of migrating most of them in bulk with a quick script. If you're actively working on a few projects and you'd prefer to migrate them yourself sooner, though, that would be just fine :smile:

I'm tracking that work in rackerlabs/nexus-control#346.

**Comment by smashwilson** [comment]
(Closing this issue in favor of that one :point_right:)
