### ISSUE TITLE
Grant access to Kyle Laffoon to see Strider build logs for the How-to and DevDoc builds on https://github.com/deconst/strider-deconst-control

### ISSUE THREAD

**Issue by kylelaffoon** [deconst/strider-deconst-control#22]
I'd like to be added to the Strider account.

**Comment by smashwilson** [comment]
:+1: I just added you to the GitHub team. Log in with OAuth at:

https://build.developer.rackspace.com/

When you first log in, you won't see any builds. The next time that the rackerlabs/nexus-control build runs (which I can kick by hand) after your initial login you'll be granted to access to everything.

**Comment by smashwilson** [comment]
Looks like we're having some memory hiccups right now. Investigating...

**Comment by smashwilson** [comment]
There we go. You should be good to go.

**Comment by kylelaffoon** [comment]
Thanks Ash!
