### ISSUE TITLE
Strider build jobs

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-control#32]
@smashwilson  Is it possible to have an equivalent method of configuring development builds on staging.horse for a jekyll repository?

**Comment by meker12** [comment]
Also, just noticed that the staging URLs on staging.horse are publicly accessible. Good to know. I thought they were private.

https://staging.developer.rackspace.com/staging.horse/build-560d60f26c/docs/cloud-paas/

**Comment by smashwilson** [comment]
> @smashwilson Is it possible to have an equivalent method of configuring development builds on staging.horse for a jekyll repository?

Yes, it should work identically. As long as you map the content ID from your `_deconst.json` file, it doesn't matter how the content was prepared.

You might need to set a different template in [routes.d](https://github.com/rackerlabs/nexus-control/blob/master/config/routes.d/staging.horse.json) but that's all.

> Also, just noticed that the staging URLs on staging.horse are publicly accessible. Good to know. I thought they were private.

That's correct; nothing served by Deconst at this time is protected by any kind of authentication. Anyone who has the link can access the content. Apologies, I thought I emphasized that more while we were setting this up!

We _do_ prevent any content on staging.developer.rackspace.com from being indexed by search engines, so staged content won't appear on Google searches and the like at least.

**Comment by meker12** [comment]
I remember now that it wasn't indexed.  Thanks for the info!
